'use strict';
(() => {
 const c=window.BOOK_CONFIG;if(!c)return;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const STORAGE_VERSION=2;const keys={theme:'bookforge-theme',reading:'bookforge-reading'};const saved=read();const state={page:1,mode:c.readingDefaults.mode,zoom:c.readingDefaults.zoom,ready:false,pdf:false,lastFocus:null,retry:0,observer:null,saveTimer:null};
 const el={drawer:$('#tocDrawer'),scrim:$('#scrim'),single:$('#singleStage'),image:$('#singleImage'),continuous:$('#continuousReader'),fallback:$('#onlineFallback'),loading:$('#readerLoading'),controls:$('#readerControls'),prev:$('#previousPage'),next:$('#nextPage'),input:$('#pageInput'),indicator:$('#pageIndicator'),percent:$('#percentRead'),progress:$('#progressBar'),live:$('#liveRegion'),error:$('#pageError')};
 function safeGet(k){try{return localStorage.getItem(k)}catch{return null}}function safeSet(k,v){try{localStorage.setItem(k,v)}catch{}}
 function read(){try{return JSON.parse(safeGet(keys.reading))||{}}catch{return{}}}function path(p){return `${c.pageImages.directory}/${c.pageImages.filenamePattern.replace('{page}',String(p).padStart(c.pageImages.digits,'0'))}`}
 function sync(){document.title=`${c.title} — Edição Digital`;const map={'[data-title]':c.title,'[data-short-title]':c.shortTitle,'[data-author]':c.author,'[data-year]':c.year,'[data-total]':c.totalPages,'[data-description]':c.description};Object.entries(map).forEach(([s,v])=>$$(s).forEach(n=>n.textContent=v));[['meta[name=description]',c.description],['meta[name=author]',c.author],['meta[property="og:title"]',c.title],['meta[property="og:description"]',c.description],['meta[name="twitter:title"]',c.title],['meta[name="twitter:description"]',c.description]].forEach(([s,v])=>$(s).content=v);const canonical=$('#canonical');if(c.publicUrl){canonical.href=c.publicUrl}else canonical.remove();const json={'@context':'https://schema.org','@type':'Book',name:c.title,author:{'@type':'Person',name:c.author},description:c.description,datePublished:String(c.year),inLanguage:'pt-BR',bookFormat:'https://schema.org/EBook',numberOfPages:c.totalPages};if(c.publicUrl)json.url=c.publicUrl;if(c.publisher)json.publisher={'@type':'Organization',name:c.publisher};$('#bookMetadata').textContent=JSON.stringify(json);$$('.pdf-download,.pdf-open').forEach(a=>a.href=c.pdfPath);$('#printPdf').href=c.pdfPath;$('#printPdf').textContent=c.pdfPath;$('#coverImage').alt=`Capa de ${c.title}`}
 const existenceCache=new Map();async function exists(url,expected){if(existenceCache.has(url))return existenceCache.get(url);const check=async(method,headers={})=>{const r=await fetch(url,{method,headers,cache:'no-store'});if(!r.ok)return false;const type=(r.headers.get('content-type')||'').toLowerCase();if(type.includes('text/html'))return false;if(expected&&type&& !type.includes(expected))return false;return true};const promise=(async()=>{try{if(await check('HEAD'))return true}catch{}try{return await check('GET',{'Range':'bytes=0-0'})}catch{return false}})();existenceCache.set(url,promise);return promise}
 function announce(t){el.live.textContent=t;el.live.classList.add('visible');clearTimeout(announce.t);announce.t=setTimeout(()=>el.live.classList.remove('visible'),2200)}
 function save(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>safeSet(keys.reading,JSON.stringify({storageVersion:STORAGE_VERSION,page:state.page,mode:state.mode,zoom:state.zoom,lastRead:new Date().toISOString()})),250)}
 function applyTheme(t,n=false){document.documentElement.dataset.theme=t;safeSet(keys.theme,t);$('meta[name=theme-color]').content=t==='dark'?c.theme.dark:c.theme.light;if(n)announce(`Tema ${t==='dark'?'escuro':'claro'} ativado.`)}
 function update(){state.page=Math.max(1,Math.min(c.totalPages,Math.round(Number(state.page)||1)));const pct=Math.round(state.page/c.totalPages*100);el.input.value=state.page;el.indicator.textContent=`Página ${state.page} de ${c.totalPages}`;el.percent.textContent=`${pct}% lido`;el.progress.style.width=`${pct}%`;el.prev.disabled=state.page===1;el.next.disabled=state.page===c.totalPages;$$('#chapterList button').forEach(b=>Number(b.dataset.page)===state.page?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));save()}
 function loadSingle(){el.error.hidden=true;el.image.hidden=false;el.image.style.opacity='1';state.retry=0;el.image.alt=`Página ${state.page} de ${c.title}`;const assign=src=>{el.image.onload=()=>{el.image.style.opacity='1';preload(state.page-1);preload(state.page+1)};el.image.onerror=()=>{if(state.retry++<1)setTimeout(()=>assign(`${path(state.page)}?retry=1`),250);else{el.image.removeAttribute('src');el.image.hidden=true;el.error.hidden=false;announce(`Não foi possível carregar a página ${state.page}.`)}};el.image.src=src};assign(path(state.page))}
 function preload(p){if(p<1||p>c.totalPages)return;const i=new Image();i.decoding='async';i.src=path(p)}
 function go(p,focus=true){state.page=Math.max(1,Math.min(c.totalPages,Number(p)||1));update();if(state.mode==='single')loadSingle();else document.querySelector(`[data-continuous-page="${state.page}"]`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(focus)announce(`Página ${state.page} de ${c.totalPages}.`)}
 function renderContinuous(){el.continuous.replaceChildren();const f=document.createDocumentFragment();for(let p=1;p<=c.totalPages;p++){const fig=document.createElement('figure');fig.dataset.continuousPage=p;const i=document.createElement('img');i.loading=p===state.page?'eager':'lazy';i.decoding='async';i.width=1600;i.height=2263;i.alt=`Página ${p} de ${c.title}`;i.onerror=()=>{i.removeAttribute('src');fig.hidden=true};i.src=path(p);const cap=document.createElement('figcaption');cap.textContent=`Página ${p}`;fig.append(i,cap);f.append(fig)}el.continuous.append(f);if('IntersectionObserver'in window){state.observer?.disconnect();state.observer=new IntersectionObserver(es=>{const x=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(x){state.page=Number(x.target.dataset.continuousPage);update()}},{threshold:[.4,.7]});$$('figure',el.continuous).forEach(x=>state.observer.observe(x))}}
 function mode(m){state.mode=m;el.single.hidden=m!=='single';el.continuous.hidden=m!=='continuous';$('#modeToggle').textContent=m==='single'?'Modo contínuo':'Página única';if(m==='continuous'){renderContinuous();setTimeout(()=>go(state.page,false),50)}else loadSingle();update()}
 function zoom(z){state.zoom=Math.max(70,Math.min(200,z));el.image.style.setProperty('--zoom',state.zoom/100);$('#zoomLabel').textContent=`${state.zoom}%`;save()}
 function openDrawer(){state.lastFocus=document.activeElement;el.drawer.classList.add('open');el.drawer.setAttribute('aria-hidden','false');$('#tocOpen').setAttribute('aria-expanded','true');el.scrim.hidden=false;document.body.style.overflow='hidden';$('#tocClose').focus()}function closeDrawer(){if(!el.drawer.classList.contains('open'))return;el.drawer.classList.remove('open');el.drawer.setAttribute('aria-hidden','true');$('#tocOpen').setAttribute('aria-expanded','false');el.scrim.hidden=true;document.body.style.overflow='';state.lastFocus?.focus()}
 function chapters(){const f=document.createDocumentFragment();c.chapters.forEach(ch=>{const li=document.createElement('li'),b=document.createElement('button'),s=document.createElement('span'),small=document.createElement('small');b.dataset.page=ch.page;s.textContent=ch.title;small.textContent=`p. ${ch.page}`;b.append(s,small);b.onclick=()=>{go(ch.page);closeDrawer()};li.append(b);f.append(li)});$('#chapterList').append(f);const tf=document.createDocumentFragment();for(let p=1;p<=c.totalPages;p++){const li=document.createElement('li'),b=document.createElement('button'),i=document.createElement('img'),s=document.createElement('small');i.loading='lazy';i.width=160;i.height=226;i.alt='';i.onerror=()=>{i.removeAttribute('src');i.hidden=true};i.src=path(p);s.textContent=`Página ${p}`;b.append(i,s);b.onclick=()=>{go(p);closeDrawer()};li.append(b);tf.append(li)}$('#thumbnailList').append(tf)}
 function tabs(pages){$('#chaptersTab').setAttribute('aria-selected',String(!pages));$('#pagesTab').setAttribute('aria-selected',String(pages));$('#chaptersPanel').hidden=pages;$('#pagesPanel').hidden=!pages}
 async function share(){const data={title:c.title,text:c.description,url:c.publicUrl||location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);announce('Endereço copiado.')}}catch(e){if(e.name!=='AbortError')announce('Não foi possível compartilhar.')}}
 function trap(e){if(e.key!=='Tab')return;const a=$$('button,input,a[href]',el.drawer).filter(x=>!x.closest('[hidden]'));if(!a.length)return;if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus()}}
 function bind(){$('#menuToggle').onclick=()=>{const n=$('#mainNav'),v=!n.classList.contains('open');n.classList.toggle('open',v);$('#menuToggle').setAttribute('aria-expanded',String(v))};$('#tocOpen').onclick=openDrawer;$('#readerToc').onclick=openDrawer;$('#tocClose').onclick=closeDrawer;el.scrim.onclick=closeDrawer;el.drawer.onkeydown=trap;$('#chaptersTab').onclick=()=>tabs(false);$('#pagesTab').onclick=()=>tabs(true);$('#chapterSearch').oninput=e=>{$$('#chapterList li').forEach(li=>li.hidden=!li.textContent.toLowerCase().includes(e.target.value.toLowerCase()))};el.prev.onclick=()=>go(state.page-1);el.next.onclick=()=>go(state.page+1);$('#pageForm').onsubmit=e=>{e.preventDefault();go(el.input.value)};$('#zoomOut').onclick=()=>zoom(state.zoom-10);$('#zoomIn').onclick=()=>zoom(state.zoom+10);$('#zoomReset').onclick=()=>zoom(100);$('#fitWidth').onclick=()=>zoom(100);$('#modeToggle').onclick=()=>mode(state.mode==='single'?'continuous':'single');$('#themeToggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark',true);$('#shareButton').onclick=share;$('#aboutShare').onclick=share;$('#fullscreenButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('#readerShell').requestFullscreen?.();addEventListener('scroll',()=>$('.topbar').classList.toggle('scrolled',scrollY>24),{passive:true});document.onkeydown=e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openDrawer();$('#chapterSearch').focus()}else if(e.key==='Escape')closeDrawer();else if(e.key==='ArrowLeft')go(state.page-1);else if(e.key==='ArrowRight')go(state.page+1);else if(e.key==='Home'){e.preventDefault();go(1)}else if(e.key==='End'){e.preventDefault();go(c.totalPages)}else if(e.key.toLowerCase()==='s')openDrawer();else if(e.key.toLowerCase()==='d')$('#themeToggle').click();else if(e.key.toLowerCase()==='f')$('#fullscreenButton').click()};let x,y;$('#readerShell').addEventListener('touchstart',e=>{x=e.touches[0].clientX;y=e.touches[0].clientY},{passive:true});$('#readerShell').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)go(state.page+(dx<0?1:-1))},{passive:true})}
 async function init(){sync();chapters();bind();applyTheme(safeGet(keys.theme)||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));const cover=$('#coverImage'),skeleton=$('#coverSkeleton');cover.onload=()=>{skeleton.hidden=true;cover.hidden=false};cover.onerror=()=>{cover.removeAttribute('src');cover.hidden=true;skeleton.hidden=false};cover.src=c.coverImage;const [images,pdf]=await Promise.all([exists(c.coverImage,'image/'),exists(c.pdfPath,'application/pdf')]);state.pdf=pdf;el.loading.hidden=true;el.controls.hidden=true;el.fallback.hidden=true;el.single.hidden=true;el.continuous.hidden=true;$('#resumeBanner').hidden=true;if(!pdf){$$('.pdf-download,.pdf-open').forEach(a=>{a.removeAttribute('href');a.setAttribute('aria-disabled','true')});$('#pdfMissing').hidden=false}if(images){state.ready=true;state.page=saved.page;state.mode=saved.mode;state.zoom=saved.zoom;el.controls.hidden=false;mode(state.mode);zoom(state.zoom);if(Number.isInteger(state.page)&&state.page>=2&&state.page<=c.totalPages){$('#resumePage').textContent=String(state.page);$('#resumeBanner').hidden=false;$('#resumeButton').onclick=()=>{$('#resumeBanner').hidden=true;go(state.page)};$('#restartButton').onclick=()=>{$('#resumeBanner').hidden=true;go(1)};$('#dismissResume').onclick=()=>$('#resumeBanner').hidden=true}}else{el.fallback.hidden=false;el.indicator.textContent='Leitura online em preparação';el.percent.textContent=pdf?'PDF disponível':'Arquivos indisponíveis'}}
 init();
})();
